version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  build_deploy:
    jobs:
      - build
      - secrets_check
      - inheritance_security_check
      - deploy_production:
          requires:
            - build
            - secrets_check
            - inheritance_security_check

jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  deploy_production:
    environment:
      HEROKU_APP_NAME: "workshop-cicd-production"
    executor: heroku/default
    steps:

      - checkout
      - heroku/install
      - heroku/deploy-via-git:

          only-branch: master
  
  secrets_check:

    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing Git Secrets
          command: |
            git clone https://github.com/awslabs/git-secrets.git git-secrets
            cd git-secrets && sudo make install && cd .. && rm -rf git-secrets
      - run:
          name: Adding Git Secrets providers
          command: "git secrets --register-aws"
      - run:
          name: Secrets check
          command: "git secrets --scan"

inheritance_security_check:
  docker:
    - image: circleci/node
  working_directory: ~/repo
  steps:
    - checkout
    - run: yarn install
    - run: yarn inheritance-security-check