version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  build_deploy:
    jobs:
      - build
      - deploy_production:
        requires:
          - build

jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  deploy_production:
    environment:
      HEROKU_APP_NAME: workshop-cicd-production
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
