version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  build_deploy:
    jobs:
      - build
      - secrets_check
      - inheritance_security_check

      - deploy_staging:
          requires:
            - build
            - secrets_check
            - inheritance_security_check
      - dast_check:
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - dast_check
          
jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  deploy_production:
    environment:
      HEROKU_APP_NAME: "workshop-cicd-production"
    executor: heroku/default
    steps:

      - checkout
      - heroku/install
      - heroku/deploy-via-git:

          only-branch: master
  
  deploy_staging:
    environment:
      HEROKU_APP_NAME: "workshop-cicd-staging"
    executor: heroku/default
    steps:

      - checkout
      - heroku/install
      - heroku/deploy-via-git:

          only-branch: master
  
  secrets_check:

    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing Git Secrets
          command: |
            git clone https://github.com/awslabs/git-secrets.git git-secrets
            cd git-secrets && sudo make install && cd .. && rm -rf git-secrets
      - run:
          name: Adding Git Secrets providers
          command: "git secrets --register-aws"
      - run:
          name: Secrets check
          command: "git secrets --scan"

  inheritance_security_check:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn inheritance-security-check

  dast_check:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: Cloning Vaddy
          command: "git clone https://github.com/vaddy/go-vaddy.git"
      - run:
          name: Security check
          command: |
            cd ./go-vaddy/bin/
            ./vaddy-linux-64bit"