version: 2.1

workflows:
  build_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
  
      - checkout
      - run: yarn install
      - run: yarn test

  